export const ADD_REMAINDER_REQUEST = 'ADD_REMAINDER_REQUEST';
export const ADD_REMAINDER_SUCCESS = 'ADD_REMAINDER_SUCCESS';
export const ADD_REMAINDER_FAILURE = 'ADD_REMAINDER_FAILURE';

export const ADD_REMAINDER = 'ADD_REMAINDER';